[supervisord]
nodaemon=true

[program:apache-foreground]
command=apache2-foreground
autostart=true
autorestart=true
user=root
stdout_logfile=/var/www/html/storage/logs/apache.log
redirect_stderr=true

[program:app-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=120
directory=/var/www/html
autostart=true
autorestart=true
numprocs=2
redirect_stderr=true
user=root
stdout_logfile=/var/www/html/storage/logs/worker.log

[program:app-task-scheduler]
command=/bin/sh -c "while true; do php /var/www/html/artisan schedule:run --verbose --no-interaction; sleep 60; done"
directory=/var/www/html
autostart=true
autorestart=true
redirect_stderr=true
user=root
stdout_logfile=/var/www/html/storage/logs/task-scheduler.log